// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WinUIEssentials
{
    internal sealed partial class Vsix
    {
        public const string Id = "WinUIEssentials.48e23162-cc0c-421b-a3ae-6982cb86c7a9";
        public const string Name = "WinUI Essentials";
        public const string Description = @"The easiest way to set up Visual Studio for the ultimate WinUI development experience.";
        public const string Language = "en-US";
        public const string Version = "1.3.1";
        public const string Author = "Matt Lacey";
        public const string Tags = "WinUI";
    }
}
